//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCaNhanPhatTrienUDW_WebBanPhuKienMayTinh_63134331.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Project_63134331Entities : DbContext
    {
        public Project_63134331Entities()
            : base("name=Project_63134331Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAIVIET> BAIVIET { get; set; }
        public virtual DbSet<CHITIETGIOHANG> CHITIETGIOHANG { get; set; }
        public virtual DbSet<CHITIETHOADON> CHITIETHOADON { get; set; }
        public virtual DbSet<HOADON> HOADON { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANG { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAM { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAP { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<SANPHAM> SANPHAM { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<DSSPTheoLoaiSP_Result> DSSPTheoLoaiSP(string loaiSP)
        {
            var loaiSPParameter = loaiSP != null ?
                new ObjectParameter("LoaiSP", loaiSP) :
                new ObjectParameter("LoaiSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSSPTheoLoaiSP_Result>("DSSPTheoLoaiSP", loaiSPParameter);
        }
    
        public virtual ObjectResult<GioHangKH_Result> GioHangKH(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GioHangKH_Result>("GioHangKH", usernameParameter);
        }
    
        public virtual int KhachHang_TimKiem(string hOTENKH, string dIACHIKH, string eMAILKH, string sDTKH)
        {
            var hOTENKHParameter = hOTENKH != null ?
                new ObjectParameter("HOTENKH", hOTENKH) :
                new ObjectParameter("HOTENKH", typeof(string));
    
            var dIACHIKHParameter = dIACHIKH != null ?
                new ObjectParameter("DIACHIKH", dIACHIKH) :
                new ObjectParameter("DIACHIKH", typeof(string));
    
            var eMAILKHParameter = eMAILKH != null ?
                new ObjectParameter("EMAILKH", eMAILKH) :
                new ObjectParameter("EMAILKH", typeof(string));
    
            var sDTKHParameter = sDTKH != null ?
                new ObjectParameter("SDTKH", sDTKH) :
                new ObjectParameter("SDTKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KhachHang_TimKiem", hOTENKHParameter, dIACHIKHParameter, eMAILKHParameter, sDTKHParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> KHDangNhap(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("KHDangNhap", usernameParameter, passwordParameter);
        }
    
        public virtual int NhanVien_TimKiem(string iDNV, string hOTENNV, string sDTNV, string eMAILNV, string dIACHINV)
        {
            var iDNVParameter = iDNV != null ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(string));
    
            var hOTENNVParameter = hOTENNV != null ?
                new ObjectParameter("HOTENNV", hOTENNV) :
                new ObjectParameter("HOTENNV", typeof(string));
    
            var sDTNVParameter = sDTNV != null ?
                new ObjectParameter("SDTNV", sDTNV) :
                new ObjectParameter("SDTNV", typeof(string));
    
            var eMAILNVParameter = eMAILNV != null ?
                new ObjectParameter("EMAILNV", eMAILNV) :
                new ObjectParameter("EMAILNV", typeof(string));
    
            var dIACHINVParameter = dIACHINV != null ?
                new ObjectParameter("DIACHINV", dIACHINV) :
                new ObjectParameter("DIACHINV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVien_TimKiem", iDNVParameter, hOTENNVParameter, sDTNVParameter, eMAILNVParameter, dIACHINVParameter);
        }
    
        public virtual ObjectResult<NVDangNhap_Result> NVDangNhap(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NVDangNhap_Result>("NVDangNhap", usernameParameter, passwordParameter);
        }
    
        public virtual int SanPham_TimKiem(string iDSP, string tENSP, string gIASPMIN, string gIASPMAX, string sOLUONG, string bH, string iMGSP)
        {
            var iDSPParameter = iDSP != null ?
                new ObjectParameter("IDSP", iDSP) :
                new ObjectParameter("IDSP", typeof(string));
    
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var gIASPMINParameter = gIASPMIN != null ?
                new ObjectParameter("GIASPMIN", gIASPMIN) :
                new ObjectParameter("GIASPMIN", typeof(string));
    
            var gIASPMAXParameter = gIASPMAX != null ?
                new ObjectParameter("GIASPMAX", gIASPMAX) :
                new ObjectParameter("GIASPMAX", typeof(string));
    
            var sOLUONGParameter = sOLUONG != null ?
                new ObjectParameter("SOLUONG", sOLUONG) :
                new ObjectParameter("SOLUONG", typeof(string));
    
            var bHParameter = bH != null ?
                new ObjectParameter("BH", bH) :
                new ObjectParameter("BH", typeof(string));
    
            var iMGSPParameter = iMGSP != null ?
                new ObjectParameter("IMGSP", iMGSP) :
                new ObjectParameter("IMGSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SanPham_TimKiem", iDSPParameter, tENSPParameter, gIASPMINParameter, gIASPMAXParameter, sOLUONGParameter, bHParameter, iMGSPParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SLSPTrongGH(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SLSPTrongGH", usernameParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
